import type { ArtId } from '../artwork/catalog';
// Quality-reminder defaults for newly bought, unopened food; not guarantees of safety.
// References and deliberate product assumptions are recorded in docs/freshness.md.
export type Days = { pantry?: number; fridge?: number; freezer?: number };
export const profiles: Partial<Record<ArtId, Days>> = {
  eggs: { fridge: 35 },
  milk: { fridge: 7 },
  butter: { fridge: 90, freezer: 270 },
  yogurt: { fridge: 30 },
  cheddar: { fridge: 180, freezer: 240 },
  mozzarella: { fridge: 30 },
  'cream-cheese': { fridge: 14 },
  'sour-cream': { fridge: 21 },
  'heavy-cream': { fridge: 7 },
  'cottage-cheese': { fridge: 7 },
  greens: { fridge: 7 },
  carrots: { fridge: 21 },
  apple: { pantry: 14, fridge: 28 },
  bananas: { pantry: 7, fridge: 2 },
  orange: { pantry: 10, fridge: 14 },
  lemon: { pantry: 10, fridge: 14 },
  lime: { pantry: 10, fridge: 14 },
  avocado: { pantry: 5, fridge: 5 },
  tomato: { pantry: 5, fridge: 6 },
  cucumber: { fridge: 5 },
  'bell-pepper': { fridge: 5 },
  broccoli: { fridge: 5 },
  cauliflower: { fridge: 5 },
  mushrooms: { fridge: 3 },
  strawberries: { fridge: 2 },
  blueberries: { fridge: 2 },
  grapes: { fridge: 7 },
  celery: { fridge: 14 },
  zucchini: { fridge: 5 },
  'green-onions': { fridge: 14 },
  fish: { fridge: 2, freezer: 90 },
  chicken: { fridge: 2, freezer: 270 },
  'ground-beef': { fridge: 2, freezer: 120 },
  bacon: { fridge: 7, freezer: 30 },
  'deli-turkey': { fridge: 14, freezer: 60 },
  sausage: { fridge: 2, freezer: 60 },
  tofu: { fridge: 7 },
  hummus: { fridge: 7 },
  'orange-juice': { fridge: 7 },
  tortillas: { pantry: 4, fridge: 14, freezer: 90 },
  bread: { pantry: 4, fridge: 14, freezer: 90 },
  can: { pantry: 730 },
  pasta: { pantry: 730 },
  rice: { pantry: 365 },
  oats: { pantry: 180 },
  flour: { pantry: 365 },
  sugar: { pantry: 540 },
  'brown-sugar': { pantry: 120 },
  cereal: { pantry: 365 },
  crackers: { pantry: 240 },
  chips: { pantry: 60 },
  'tortilla-chips': { pantry: 60 },
  pretzels: { pantry: 180 },
  popcorn: { pantry: 365 },
  nuts: { pantry: 120 },
  'peanut-butter': { pantry: 270 },
  jam: { pantry: 365 },
  honey: { pantry: 365 },
  'olive-oil': { pantry: 180 },
  'vegetable-oil': { pantry: 180 },
  vinegar: { pantry: 730 },
  'soy-sauce': { pantry: 365 },
  'hot-sauce': { pantry: 365 },
  ketchup: { pantry: 365 },
  mustard: { pantry: 365 },
  mayonnaise: { pantry: 120 },
  salsa: { pantry: 540 },
  'pasta-sauce': { pantry: 540 },
  'canned-tomatoes': { pantry: 540 },
  'canned-corn': { pantry: 730 },
  'canned-peas': { pantry: 730 },
  chickpeas: { pantry: 730 },
  'kidney-beans': { pantry: 730 },
  lentils: { pantry: 365 },
  tuna: { pantry: 730 },
  soup: { pantry: 730 },
  broth: { pantry: 365 },
  'coconut-milk': { pantry: 365 },
  coffee: { pantry: 730 },
  tea: { pantry: 540 },
  cocoa: { pantry: 240 },
  chocolate: { pantry: 730 },
  cookies: { pantry: 60 },
  raisins: { pantry: 365 },
  granola: { pantry: 180 },
  quinoa: { pantry: 365 },
  potatoes: { pantry: 60 },
  onions: { pantry: 30 },
  garlic: { pantry: 30 },
  'sweet-potatoes': { pantry: 30 },
  'frozen-peas': { freezer: 365 },
  'frozen-corn': { freezer: 365 },
  'frozen-broccoli': { freezer: 365 },
  'frozen-berries': { freezer: 365 },
  'frozen-pizza': { freezer: 60 },
  'ice-cream': { freezer: 60 },
  'frozen-fries': { freezer: 180 },
  'frozen-waffles': { freezer: 30 },
  'frozen-dumplings': { freezer: 90 },
  'frozen-shrimp': { freezer: 180 },
};
