import { fridgeArt } from '../artwork/fridge';
import { pantryArt } from '../artwork/pantry';
import { freezerArt } from '../artwork/freezer';
import { normalizeIngredientName } from '../recipes/names';
import curatedFoods from './curated-foods.json';

const extraFoods = [
  'kosher salt',
  'sea salt',
  'table salt',
  'garlic cloves',
  'garlic powder',
  'onion powder',
  'smoked paprika',
  'cayenne pepper',
  'ground black pepper',
  'water',
  'salt',
  'pepper',
  'black pepper',
  'white pepper',
  'chili powder',
  'cumin',
  'paprika',
  'cinnamon',
  'basil',
  'oregano',
  'thyme',
  'rosemary',
  'parsley',
  'cilantro',
  'ginger',
  'turmeric',
  'baking powder',
  'baking soda',
  'yeast',
  'cornstarch',
  'vanilla extract',
  'lemon juice',
  'lime juice',
  'orange zest',
  'lemon zest',
  'sesame oil',
  'canola oil',
  'coconut oil',
  'spinach',
  'kale',
  'lettuce',
  'salad greens',
  'arugula',
  'cabbage',
  'asparagus',
  'eggplant',
  'peas',
  'corn',
  'green beans',
  'beans',
  'pinto beans',
  'white beans',
  'cannellini beans',
  'garbanzo beans',
  'red lentils',
  'brown lentils',
  'brown rice',
  'white rice',
  'basmati rice',
  'jasmine rice',
  'long-grain rice',
  'short-grain rice',
  'wild rice',
  'spaghetti',
  'penne',
  'macaroni',
  'linguine',
  'fettuccine',
  'fusilli',
  'rigatoni',
  'gluten-free pasta',
  'whole wheat pasta',
  'noodles',
  'couscous',
  'barley',
  'bulgur',
  'rolled oats',
  'all-purpose flour',
  'whole wheat flour',
  'breadcrumbs',
  'beef',
  'pork',
  'turkey',
  'chicken breast',
  'chicken thighs',
  'salmon',
  'cod',
  'shrimp',
  'sardines',
  'oysters',
  'mackerel',
  'anchovies',
  'ham',
  'seitan',
  'tempeh',
  'cheese',
  'parmesan',
  'feta',
  'ricotta',
  'cream',
  'greek yogurt',
  'almond milk',
  'oat milk',
  'soy milk',
  'almonds',
  'walnuts',
  'peanuts',
  'cashews',
  'sesame seeds',
  'sunflower seeds',
  'pumpkin seeds',
  'cherries',
  'peaches',
  'pears',
  'pineapple',
  'mango',
  'kiwi',
  'plums',
  'apples',
  'oranges',
  'lemons',
  'limes',
  'avocados',
  'cucumbers',
  'chicken broth',
  'vegetable broth',
  'beef broth',
  'tomato paste',
  'tomato sauce',
  'red wine',
  'white wine',
  'rice vinegar',
  'apple cider vinegar',
  'balsamic vinegar',
  'maple syrup',
  'tahini',
];
const names = new Set(
  [...fridgeArt, ...pantryArt, ...freezerArt]
    .map(([, label]) => label.replace(/\b(carton|cup|can|box|bag|tub|bottle)\b/gi, '').trim())
    .concat(extraFoods, curatedFoods)
    .map(normalizeIngredientName),
);
const preparations =
  /\b(fresh|frozen|canned|dried|dry|cooked|raw|uncooked|chopped|diced|sliced|grated|shredded|peeled|boneless|skinless|organic|unsalted|salted|drained|rinsed)\b/g;

// Deliberately conservative: artwork or a food flag alone does not make a name edible.
// Unknown brands, ambiguous custom labels, and nonfood text stay out of AI suggestions.
export function isRecipeFoodName(name: string): boolean {
  if (!/^[\p{L}\d][\p{L}\d '-]*$/u.test(name) || name.length > 80) return false;
  const normalized = normalizeIngredientName(name);
  if (names.has(normalized)) return true;
  return names.has(normalizeIngredientName(normalized.replace(preparations, '').trim()));
}
