import { fridgeArt } from '../domain/artwork/fridge';
import { pantryArt } from '../domain/artwork/pantry';
import { freezerArt } from '../domain/artwork/freezer';
import { isRecipeFoodName } from '../domain/recipe-suggestions/foods';

const initial = [
  'Canned black beans',
  'Canned pinto beans',
  'Dried black beans',
  'Brown rice',
  'White rice',
  'Jasmine rice',
  'Spaghetti',
  'Penne',
  'Frozen peas',
  'Frozen carrots',
];
const varieties = [
  'Canned kidney beans',
  'Canned cannellini beans',
  'Dried pinto beans',
  'Cooked brown rice',
  'Cooked white rice',
  'Basmati rice',
  'Short-grain rice',
  'Macaroni',
  'Fusilli',
  'Gluten-free pasta',
  'Tomatoes',
  'Canned tomatoes',
  'Cucumbers',
  'Onions',
  'Garlic',
  'Broccoli',
  'Frozen broccoli',
  'Eggs',
  'Milk',
  'Butter',
  'Potatoes',
  'Carrots',
  'Olive oil',
  'Salt',
  'Black pepper',
  'Cheese',
  'Tofu',
  'Chicken',
  'Spinach',
  'Frozen spinach',
];
const extras = [
  'Pinto beans',
  'White beans',
  'Cannellini beans',
  'Red lentils',
  'Brown lentils',
  'Long-grain rice',
  'Linguine',
  'Fettuccine',
  'Rigatoni',
  'Whole wheat pasta',
  'Noodles',
  'Couscous',
  'Barley',
  'Bulgur',
  'Rolled oats',
  'All-purpose flour',
  'Whole wheat flour',
  'Breadcrumbs',
  'Beef',
  'Pork',
  'Turkey',
  'Chicken breast',
  'Chicken thighs',
  'Salmon',
  'Cod',
  'Shrimp',
  'Sardines',
  'Oysters',
  'Mackerel',
  'Anchovies',
  'Ham',
  'Seitan',
  'Tempeh',
  'Parmesan',
  'Feta',
  'Ricotta',
  'Cream',
  'Greek yogurt',
  'Almond milk',
  'Oat milk',
  'Soy milk',
  'Almonds',
  'Walnuts',
  'Peanuts',
  'Cashews',
  'Sesame seeds',
  'Sunflower seeds',
  'Pumpkin seeds',
  'Cherries',
  'Peaches',
  'Pears',
  'Pineapple',
  'Mango',
  'Kiwi',
  'Plums',
  'Apples',
  'Oranges',
  'Lemons',
  'Limes',
  'Avocados',
  'Chicken broth',
  'Vegetable broth',
  'Beef broth',
  'Tomato paste',
  'Tomato sauce',
  'Red wine',
  'White wine',
  'Rice vinegar',
  'Apple cider vinegar',
  'Balsamic vinegar',
  'Maple syrup',
  'Tahini',
  'Kale',
  'Lettuce',
  'Salad greens',
  'Arugula',
  'Cabbage',
  'Asparagus',
  'Eggplant',
  'Peas',
  'Corn',
  'Green beans',
  'Kosher salt',
  'Sea salt',
  'Garlic cloves',
  'Garlic powder',
  'Onion powder',
  'Smoked paprika',
  'Cayenne pepper',
  'Cumin',
  'Paprika',
  'Cinnamon',
  'Basil',
  'Oregano',
  'Thyme',
  'Rosemary',
  'Parsley',
  'Cilantro',
  'Ginger',
  'Turmeric',
  'Baking powder',
  'Baking soda',
  'Yeast',
  'Cornstarch',
  'Vanilla extract',
  'Lemon juice',
  'Lime juice',
  'Orange zest',
  'Lemon zest',
  'Sesame oil',
  'Canola oil',
  'Coconut oil',
];
const catalog = [...fridgeArt, ...pantryArt, ...freezerArt].map(([, label]) =>
  label.replace(/\b(carton|cup|can|box|bag|tub|bottle)\b/gi, '').trim(),
);
const frozenProduce = [
  'Broccoli',
  'Cauliflower',
  'Strawberries',
  'Blueberries',
  'Raspberries',
  'Mango',
  'Pineapple',
  'Cherries',
  'Peaches',
  'Corn',
  'Green beans',
  'Kale',
].map((name) => `Frozen ${name}`);
export const benchmarkFoodNames = [
  ...new Set([...initial, ...varieties, ...extras, ...catalog, ...frozenProduce]),
].filter(isRecipeFoodName);

export const sampleFoodNames = [
  ...new Set(['Eggs', 'Milk', 'Butter', 'Black beans', 'Rice', 'Pasta', ...benchmarkFoodNames]),
].slice(0, 200);
