// Generated by pnpm artwork:generate from authored SVG recipes.
export const freezerArt = [
  ['frozen-peas', 'Frozen peas', '/art/freezer/1/frozen-peas.svg', 'frozen-bag'],
  ['frozen-corn', 'Frozen corn', '/art/freezer/1/frozen-corn.svg', 'frozen-bag'],
  ['frozen-broccoli', 'Frozen broccoli', '/art/freezer/1/frozen-broccoli.svg', 'frozen-bag'],
  ['frozen-berries', 'Frozen berries', '/art/freezer/1/frozen-berries.svg', 'frozen-bag'],
  ['frozen-pizza', 'Frozen pizza', '/art/freezer/1/frozen-pizza.svg', 'pizza'],
  ['ice-cream', 'Ice cream', '/art/freezer/1/ice-cream.svg', 'tub'],
  ['frozen-fries', 'Frozen fries', '/art/freezer/1/frozen-fries.svg', 'frozen-bag'],
  ['frozen-waffles', 'Frozen waffles', '/art/freezer/1/frozen-waffles.svg', 'box'],
  ['frozen-dumplings', 'Frozen dumplings', '/art/freezer/1/frozen-dumplings.svg', 'frozen-bag'],
  ['frozen-shrimp', 'Frozen shrimp', '/art/freezer/1/frozen-shrimp.svg', 'frozen-bag'],
] as const;
