// Generated by pnpm artwork:generate from authored SVG recipes.
export const householdArt = [
  ['napkins', 'Napkins', '/art/household/1/napkins.svg', 'household'],
  ['paper-towels', 'Paper towels', '/art/household/1/paper-towels.svg', 'household'],
  ['paper-plates', 'Paper plates', '/art/household/1/paper-plates.svg', 'household'],
  ['toilet-paper', 'Toilet paper', '/art/household/1/toilet-paper.svg', 'household'],
  ['shaving-cream', 'Shaving cream', '/art/household/1/shaving-cream.svg', 'household'],
  ['household-box', 'Storage box', '/art/household/1/household-box.svg', 'household'],
] as const;
