// Generated by pnpm artwork:generate from authored SVG recipes.
export const packagingArt = [
  ['generic', 'Grocery bag', '/art/generic.svg', 'grocery'],
  ['plain-can', 'Plain can', '/art/packaging/1/plain-can.svg', 'can'],
  ['plain-tin', 'Plain seafood tin', '/art/packaging/1/plain-tin.svg', 'tin'],
  ['plain-box', 'Plain box', '/art/packaging/1/plain-box.svg', 'box'],
  ['plain-bag', 'Plain snack bag', '/art/packaging/1/plain-bag.svg', 'bag'],
  ['plain-jar', 'Plain jar', '/art/packaging/1/plain-jar.svg', 'jar'],
  ['plain-bottle', 'Plain bottle', '/art/packaging/1/plain-bottle.svg', 'bottle'],
  ['plain-carton', 'Plain carton', '/art/packaging/1/plain-carton.svg', 'carton'],
] as const;
