// Authored illustration recipes. IDs are persistent food values; never rename existing IDs.
// Each recipe: id, picker label, silhouette, primary ink, accent ink, package illustration.
import { plainBottles } from './drinks.mjs';

export const fridge = [
  ['eggs', 'Egg carton', 'legacy'],
  ['milk', 'Milk carton', 'legacy'],
  ['butter', 'Butter', 'legacy'],
  ['yogurt', 'Yogurt cup', 'legacy'],
  ['cheddar', 'Cheddar cheese', 'cheese', '#e4ac4b'],
  ['mozzarella', 'Mozzarella', 'cheese', '#eee6c9'],
  ['cream-cheese', 'Cream cheese', 'tub', '#709889', '#f0e7cf', 'cheese'],
  ['sour-cream', 'Sour cream', 'tub', '#7495ad', '#f1ead8', 'cream'],
  ['heavy-cream', 'Heavy cream', 'carton', '#b8796e', '#f0e3c5', 'cream'],
  ['cottage-cheese', 'Cottage cheese', 'tub', '#a29e70', '#f4eddb', 'curds'],
  ['greens', 'Leafy greens', 'legacy'],
  ['carrots', 'Carrots', 'legacy'],
  ['apple', 'Apple', 'legacy'],
  ['bananas', 'Bananas', 'produce'],
  ['orange', 'Orange', 'produce'],
  ['lemon', 'Lemon', 'produce'],
  ['lime', 'Lime', 'produce'],
  ['avocado', 'Avocado', 'produce'],
  ['tomato', 'Tomato', 'produce'],
  ['cucumber', 'Cucumber', 'produce'],
  ['bell-pepper', 'Bell pepper', 'produce'],
  ['broccoli', 'Broccoli', 'produce'],
  ['cauliflower', 'Cauliflower', 'produce'],
  ['mushrooms', 'Mushrooms', 'produce'],
  ['strawberries', 'Strawberries', 'produce'],
  ['blueberries', 'Blueberries', 'produce'],
  ['grapes', 'Grapes', 'produce'],
  ['celery', 'Celery', 'produce'],
  ['zucchini', 'Zucchini', 'produce'],
  ['green-onions', 'Green onions', 'produce'],
  ['fish', 'Fish', 'legacy'],
  ['chicken', 'Chicken', 'protein', '#e3ab8f', '#b46f55', 'chicken'],
  ['ground-beef', 'Ground beef', 'protein', '#ad6c60', '#864b44', 'mince'],
  ['bacon', 'Bacon', 'protein', '#b76c5b', '#f0c3a1', 'bacon'],
  ['deli-turkey', 'Deli turkey', 'protein', '#e3b99b', '#bc8f72', 'slices'],
  ['sausage', 'Sausages', 'protein', '#b78160', '#8e5b44', 'sausage'],
  ['tofu', 'Tofu', 'protein', '#f0e6ca', '#b0ac88', 'tofu'],
  ['hummus', 'Hummus', 'tub', '#c7a269', '#efe2c5', 'hummus'],
  ['orange-juice', 'Orange juice', 'carton', '#d79d47', '#f6e2b1', 'citrus'],
  ['tortillas', 'Tortillas', 'stack', '#e4c893', '#b89962', 'tortilla'],
];

export const pantry = [
  ['can', 'Black beans can', 'legacy'],
  ['pasta', 'Pasta box', 'legacy'],
  ['rice', 'Rice bag', 'legacy'],
  ['oats', 'Oats tub', 'legacy'],
  ['bread', 'Bread', 'legacy'],
  ['flour', 'Flour', 'sack', '#ded0b1', '#a58b65', 'wheat'],
  ['sugar', 'Sugar', 'sack', '#9eaeb5', '#f2ead8', 'cubes'],
  ['brown-sugar', 'Brown sugar', 'sack', '#c1a27b', '#f2dfbb', 'cubes'],
  ['cereal', 'Cereal', 'box', '#c69563', '#f3dfb5', 'cereal'],
  ['crackers', 'Crackers', 'box', '#b97b58', '#f0d8a7', 'cracker'],
  ['chips', 'Potato chips', 'bag', '#d7b06a', '#8d9a70', 'chips'],
  ['tortilla-chips', 'Tortilla chips', 'bag', '#af7960', '#ebcd8f', 'triangles'],
  ['pretzels', 'Pretzels', 'bag', '#b79c76', '#e8d2a9', 'pretzel'],
  ['popcorn', 'Popcorn', 'bag', '#a57567', '#f0d7a5', 'popcorn'],
  ['nuts', 'Mixed nuts', 'bag', '#a1a47a', '#f1debb', 'nuts'],
  ['peanut-butter', 'Peanut butter', 'jar', '#bd915b', '#9d6651', 'peanut'],
  ['jam', 'Jam', 'jar', '#b57879', '#ddd0ad', 'berries'],
  ['honey', 'Honey', 'jar', '#d5a54f', '#b58c50', 'honey'],
  ['olive-oil', 'Olive oil', 'bottle', '#839261', '#e5d5ad', 'olives'],
  ['vegetable-oil', 'Vegetable oil', 'bottle', '#d5b668', '#dcd3b3', 'drop'],
  ['vinegar', 'Vinegar', 'bottle', '#c8b083', '#f1e6cb', 'drop'],
  ['soy-sauce', 'Soy sauce', 'bottle', '#6c5545', '#be8670', 'beans'],
  ['hot-sauce', 'Hot sauce', 'bottle', '#b96448', '#e4cd9c', 'chili'],
  ['ketchup', 'Ketchup', 'squeeze', '#b96451', '#e6d2a5', 'tomato'],
  ['mustard', 'Mustard', 'squeeze', '#d2ab4e', '#eee0b9', 'seed'],
  ['mayonnaise', 'Mayonnaise', 'jar', '#ede3c2', '#78929d', 'cream'],
  ['salsa', 'Salsa', 'jar', '#b77451', '#8d9b6d', 'tomato'],
  ['pasta-sauce', 'Pasta sauce', 'jar', '#b56c50', '#9e8461', 'tomato'],
  ['canned-tomatoes', 'Canned tomatoes', 'can', '#b96c53', '#f0ddba', 'tomato'],
  ['canned-corn', 'Canned corn', 'can', '#cfb468', '#f3e5ba', 'corn'],
  ['canned-peas', 'Canned peas', 'can', '#8a9c72', '#ede1bc', 'peas'],
  ['chickpeas', 'Chickpeas', 'can', '#b4a079', '#f0dfb5', 'chickpeas'],
  ['kidney-beans', 'Kidney beans', 'can', '#a87966', '#eedcba', 'beans'],
  ['lentils', 'Lentils', 'sack', '#a7a17b', '#ecdfbd', 'lentils'],
  ['tuna', 'Tuna', 'tin', '#8097a3', '#e9ddbc', 'fish'],
  ['soup', 'Soup', 'can', '#ae805f', '#ecdfbd', 'soup'],
  ['broth', 'Broth', 'carton', '#c39c61', '#e5d4aa', 'soup'],
  ['coconut-milk', 'Coconut milk', 'can', '#859c88', '#f1e7cd', 'coconut'],
  ['coffee', 'Coffee', 'sack', '#97785f', '#e6d5b1', 'coffee'],
  ['tea', 'Tea', 'box', '#8f9b73', '#e4d9b9', 'tea'],
  ['cocoa', 'Cocoa', 'tub', '#99735c', '#e9d9b6', 'cocoa'],
  ['chocolate', 'Chocolate', 'bar', '#715547', '#b29679', 'chocolate'],
  ['cookies', 'Cookies', 'box', '#b79168', '#ecddb9', 'cookie'],
  ['raisins', 'Raisins', 'box', '#9d7a74', '#e7d7b9', 'raisins'],
  ['granola', 'Granola', 'sack', '#ab9b77', '#ead9b3', 'granola'],
  ['quinoa', 'Quinoa', 'sack', '#ae9879', '#f0e4c7', 'quinoa'],
  ['potatoes', 'Potatoes', 'produce'],
  ['onions', 'Onions', 'produce'],
  ['garlic', 'Garlic', 'produce'],
  ['sweet-potatoes', 'Sweet potatoes', 'produce'],
];

export const freezer = [
  ['frozen-peas', 'Frozen peas', 'frozen-bag', '#94aa93', '#e7f0e8', 'peas'],
  ['frozen-corn', 'Frozen corn', 'frozen-bag', '#bdba85', '#eef1de', 'corn'],
  ['frozen-broccoli', 'Frozen broccoli', 'frozen-bag', '#8caaa0', '#e1eee7', 'broccoli'],
  ['frozen-berries', 'Frozen berries', 'frozen-bag', '#a496ab', '#eee4ea', 'berries'],
  ['frozen-pizza', 'Frozen pizza', 'pizza', '#b87b60', '#e9d2a2', 'pizza'],
  ['ice-cream', 'Ice cream', 'tub', '#97abb6', '#f0e6d3', 'scoop'],
  ['frozen-fries', 'Frozen fries', 'frozen-bag', '#b9a676', '#efe4c4', 'fries'],
  ['frozen-waffles', 'Frozen waffles', 'box', '#b99c69', '#e1e9df', 'waffle'],
  ['frozen-dumplings', 'Frozen dumplings', 'frozen-bag', '#9baca6', '#f0e8d5', 'dumpling'],
  ['frozen-shrimp', 'Frozen shrimp', 'frozen-bag', '#bc9a8c', '#e6eeeb', 'shrimp'],
];

export const packaging = [
  ['generic', 'Grocery bag', 'grocery'],
  ['plain-can', 'Plain can', 'can', '#99a18c', '#e9e1cc', ''],
  ['plain-tin', 'Plain seafood tin', 'tin', '#a7aba2', '#e9e2d1', ''],
  ['plain-box', 'Plain box', 'box', '#bda47f', '#e9dcc0', ''],
  ['plain-bag', 'Plain snack bag', 'bag', '#bba37f', '#e9ddc4', ''],
  ['plain-jar', 'Plain jar', 'jar', '#b3ad8e', '#e7dcc4', ''],
  ['plain-bottle', 'Plain bottle', 'bottle', '#9aab91', '#e5ddc4', ''],
  ['plain-carton', 'Plain carton', 'carton', '#a1afa4', '#ede4cf', ''],
  ...plainBottles,
];
