import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, URL } from 'node:url';
import process from 'node:process';
import console from 'node:console';
import { format } from 'prettier';
import { fridge, pantry, freezer, packaging } from './catalog.mjs';
import { packageArt } from './packages.mjs';
import { produceArt } from './produce.mjs';
import { cheeseArt, proteinArt } from './protein.mjs';

const root = fileURLToPath(new URL('../../', import.meta.url));
const check = process.argv.includes('--check');
const groups = { fridge, pantry, freezer, packaging };
const escape = (value) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;');
function render(recipe) {
  const [id, label, shape] = recipe;
  const renderers = {
    produce: () => produceArt(id),
    protein: () => proteinArt(recipe),
    cheese: () => cheeseArt(recipe),
  };
  const body = renderers[shape]?.() ?? packageArt(recipe);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 70"><title>${escape(label)}</title><ellipse cx="40" cy="65" rx="24" ry="3" fill="#6b7159" opacity=".12"/><g stroke-linejoin="round" stroke-linecap="round">${body}</g></svg>\n`;
}
async function save(relative, content) {
  const file = path.join(root, relative);
  if (check) {
    if ((await readFile(file, 'utf8')).replaceAll('\r\n', '\n') !== content)
      throw new Error(`Artwork is out of date: ${relative}. Run pnpm artwork:generate.`);
    return;
  }
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, content);
}
function imagePath(recipe, group, index) {
  const [id, , shape] = recipe;
  return shape === 'legacy' || id === 'generic'
    ? `/art/${id}.svg`
    : `/art/${group}/${Math.floor(index / 18) + 1}/${id}.svg`;
}
const ids = new Set();
for (const [group, recipes] of Object.entries(groups)) {
  const entries = [];
  for (const [index, recipe] of recipes.entries()) {
    const [id, label, shape] = recipe;
    if (ids.has(id)) throw new Error(`Duplicate artwork ID: ${id}`);
    ids.add(id);
    const asset = imagePath(recipe, group, index);
    if (shape !== 'legacy') await save(`public${asset}`, render(recipe));
    else await readFile(path.join(root, `public${asset}`));
    entries.push([id, label, asset, shape]);
  }
  const source = `// Generated by pnpm artwork:generate from authored SVG recipes.\nexport const ${group}Art = ${JSON.stringify(entries)} as const;\n`;
  await save(
    `src/domain/artwork/${group}.ts`,
    await format(source, { parser: 'typescript', singleQuote: true, printWidth: 96 }),
  );
}
if (fridge.length + pantry.length + freezer.length !== 100 || freezer.length !== 10)
  throw new Error('The library must contain 100 food illustrations, including 10 freezer foods.');
console.log(
  `Artwork ${check ? 'verified' : 'generated'}: 100 foods + ${packaging.length} plain packaging options.`,
);
